### ISSUE TITLE
Support for Strapi Version 5

### ISSUE THREAD

**Issue by sulavsssmc** [oramasearch/orama-plugin-strapi#11]
Requesting the Developer's Team to provide support for version 5 of Strapi. I tried to use the Orama Plugin but was unable to do so because the project i'm using is built using Strapi Version 5 as the current plugin of Orama only support till version 4. Which is why i'm unable to use Orama for the project.

**Comment by raiindev** [comment]
Hey @sulavsssmc, the Strapi v5 plugin, among other changes, is on our roadmap and will soon be released!
As soon as it's available, I'll notice you here :)

**Comment by serman** [comment]
Hello! Do you have an estimate of when the V5 plugin version might be ready? I am choosing a search engine for a new project and Orama looks great, but I cannot use it without this plugin. 

Thanks!

**Comment by raiindev** [comment]
Hey @serman, we released the support for Strapi v5!
You can install it by using `npm install @oramacloud/plugin-strapi@latest`

**Comment by serman** [comment]
Thanks for the update. Since I wasn't sure about the plan for the plugin I decided to implement an endpoint and connect Orama using the rest API, which seems to be a better solution for me because I need a few data customizations. 

Rgds
