### ISSUE TITLE
Searchable relations

### ISSUE THREAD

**Issue by giogaspa** [oramasearch/orama-plugin-strapi#8]
Hi,

I am new to the world of Orama and Strapi and it is not clear to me how the schema of an index containing relations should be generated so that I can also search within them. 
Let me try to give an example to make myself better understood: in Strapi I have two collections, one called `Exercises` and the other `Muscles` connected to each other with a one-to-many relationship.
In this case the plugin generates an index with this schema: 

```javascript
{
  "name": "string",
  "description": "string",
  "muscles": {
    "name": "string",
    "description": "string"
  }
}
```

It should not be correct though since the relation `muscles` is not an object but is an array of objects with the form: 
```javascript
muscles: [
  { name: 'hamstring', description: '...' },
  { name: 'quadriceps', description: '...' },
  ...
]
```

I saw in the documentation that array of objects is not supported https://docs.orama.com/open-source/usage/create/#schema-properties-and-types, but how can I make Orama search inside the relations as well? Do you have any solutions in mind that can be implemented in the plugin?

**Comment by faustoq** [comment]
hi @giogaspa , yes, unfortunately the array of objects is not supported. This has to do with speed and optimization of queries to guarantee the fastest experience possible. However, having "array of objects" is pretty common, especially when including related objects like in your use case. We have been thinking about addressing this use case by giving users the possibility to transform data before creating the document to be indexed.

Ideally, this is how it would work: in the plugin's configuration you can setup a custom callback function `documentTransformer`, that can be used internally by the plugin to transform data, before sending it to Orama Cloud. e.g.

```
module.exports = ({ env }) => ({
    "orama-cloud": {
        enabled: true,
        config: {
            privateApiKey: env('ORAMA_PRIVATE_API_KEY'),
            documentTransformer: (data) => {
               // transform the muscles array of objects into an object 
               if (data?.muscles && Array.isArray(data.muscles)) {
                 return {
                   ...data,
                   muscles: Object.fromEntries(data.muscles)
                 }
               }
               return data
            },
        },
    },
});
```

In this way, you should have the freedom to manipulate the data and transform the array of objects in an object, and you should be able to search through it with the following generated schema:
```
{
  "name": "string",
  "description": "string",
  "muscles": {
    "name": "string",
    "description": "string"
  }
}
```

What do you think? 

cc: @raiindev

**Comment by faustoq** [comment]
@giogaspa Yes, indeed! In the transformer function, you can implement the logic that best fits your use case, like defining two arrays of string values (`string[]`) for searching within the relation's names and descriptions. 

We're planning to implement this feature in our next release. While we still need to refine the solution, we'll keep you updated on its progress.
